version: '3.5'

services:
  todolist-task:
    image: mysql:8.1
    container_name: todolist-task
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: todolist-task
    ports:
      - "3307:3306"
    volumes:
      - mysql_task_data:/var/lib/mysql

volumes:
  mysql_task_data:
